namespace Instalify_V3;

using Instalify_V3.Pages;
using System.Collections.Generic;

public class AppDataService
{

    
    public List<App> GetAppsByCategory(string categoryName)
    {
        List<App> apps = new List<App>
        {
            new App { Name = "Steam", Description = "Plattform für Spiele und soziale Interaktion", Command = "winget install Steam", IconClass = "bi-joystick", CategoryName = "Gaming" },
new App { Name = "Discord", Description = "Sprach- und Textchat für Gamer", Command = "winget install Discord", IconClass = "bi-discord", CategoryName = "Gaming" },
new App { Name = "Visual Studio Code", Description = "Kostenloser Code-Editor von Microsoft", Command = "winget install VisualStudioCode", IconClass = "bi-code-slash", CategoryName = "Development" },
new App { Name = "GitHub Desktop", Description = "Grafische Benutzeroberfläche für GitHub", Command = "winget install GitHubDesktop", IconClass = "bi-github", CategoryName = "Development" },
new App { Name = "Google Chrome", Description = "Webbrowser von Google", Command = "winget install Google.Chrome", IconClass = "bi-globe2", CategoryName = "Utility" },
new App { Name = "Adobe Photoshop", Description = "Bildbearbeitungssoftware", Command = "winget install Adobe.Photoshop", IconClass = "bi-image", CategoryName = "Design" },
new App { Name = "Zoom", Description = "Videokonferenzsoftware", Command = "winget install Zoom", IconClass = "bi-camera-video", CategoryName = "Communication" },
new App { Name = "Slack", Description = "Kollaborationswerkzeug für Teams", Command = "winget install Slack", IconClass = "bi-slack", CategoryName = "Communication" },
new App { Name = "Spotify", Description = "Musik-Streaming-Dienst", Command = "winget install Spotify", IconClass = "bi-music-note", CategoryName = "Media" },
new App { Name = "Microsoft Teams", Description = "Kommunikations- und Kollaborationsplattform", Command = "winget install Microsoft.Teams", IconClass = "bi-chat", CategoryName = "Communication" },
new App { Name = "Notepad++", Description = "Kostenloser Texteditor für Windows", Command = "winget install NotepadPlusPlus", IconClass = "bi-file-code", CategoryName = "Development" },
new App { Name = "Adobe Acrobat Reader", Description = "PDF-Betrachter von Adobe", Command = "winget install Adobe.AcrobatReader", IconClass = "bi-file-pdf", CategoryName = "Utility" },
new App { Name = "VLC Media Player", Description = "Mediaplayer für verschiedene Audio- und Videoformate", Command = "winget install VLC.MediaPlayer", IconClass = "bi-play-circle", CategoryName = "Media" },
new App { Name = "Dropbox", Description = "Cloud-Speicher und Dateisynchronisation", Command = "winget install Dropbox", IconClass = "bi-cloud", CategoryName = "Utility" },
new App { Name = "Evernote", Description = "Notiz-App für Notizen und Ideen", Command = "winget install Evernote", IconClass = "bi-journal", CategoryName = "Productivity" },
new App { Name = "Microsoft Office", Description = "Bürosoftware-Suite von Microsoft", Command = "winget install Microsoft.Office", IconClass = "bi-file-earmark-text", CategoryName = "Productivity" },
new App { Name = "Adobe Illustrator", Description = "Vektorgrafiksoftware von Adobe", Command = "winget install Adobe.Illustrator", IconClass = "bi-vector-pen", CategoryName = "Design" },
new App { Name = "Audacity", Description = "Kostenloser Audio-Editor und -Recorder", Command = "winget install Audacity", IconClass = "bi-mic", CategoryName = "Media" },
new App { Name = "FileZilla", Description = "Kostenloser FTP-Client", Command = "winget install FileZilla", IconClass = "bi-server", CategoryName = "Utility" },
new App { Name = "Python", Description = "Programmiersprache", Command = "winget install Python", IconClass = "bi-python", CategoryName = "Development" },
new App { Name = "Atom", Description = "Moderner Texteditor", Command = "winget install Atom", IconClass = "bi-file-richtext", CategoryName = "Development" },
new App { Name = "WinRAR", Description = "Packprogramm zur Datenkompression", Command = "winget install WinRAR", IconClass = "bi-archive", CategoryName = "Utility" },
new App { Name = "WhatsApp Desktop", Description = "Desktop-Version von WhatsApp", Command = "winget install WhatsApp", IconClass = "bi-phone", CategoryName = "Communication" },
new App { Name = "Telegram", Description = "Instant Messenger", Command = "winget install Telegram", IconClass = "bi-telegram", CategoryName = "Communication" },
new App { Name = "Microsoft OneDrive", Description = "Cloud-Speicher und Synchronisation", Command = "winget install Microsoft.OneDrive", IconClass = "bi-cloud-arrow-up", CategoryName = "Utility" },
new App { Name = "ZoomIt", Description = "Bildschirmzoom und Annotationstool", Command = "winget install ZoomIt", IconClass = "bi-zoom-in", CategoryName = "Utility" },
new App { Name = "Microsoft Edge", Description = "Webbrowser von Microsoft", Command = "winget install Microsoft.Edge", IconClass = "bi-globe", CategoryName = "Utility" },
new App { Name = "OpenVPN", Description = "Open Source VPN", Command = "winget install OpenVPN", IconClass = "bi-shield-lock", CategoryName = "Utility" },
new App { Name = "Visual Studio", Description = "Integrierte Entwicklungsumgebung (IDE)", Command = "winget install VisualStudio", IconClass = "bi-tools", CategoryName = "Development" },
new App { Name = "Sublime Text", Description = "Leistungsfähiger Texteditor für Code, Markup und Prosa", Command = "winget install SublimeText", IconClass = "bi-pencil", CategoryName = "Development" },
new App { Name = "Docker Desktop", Description = "Containerisierungsplattform", Command = "winget install DockerDesktop", IconClass = "bi-docker", CategoryName = "Development" },
new App { Name = "Microsoft Visio", Description = "Diagramm- und Flussdiagrammerstellungsprogramm", Command = "winget install Microsoft.Visio", IconClass = "bi-diagram-2", CategoryName = "Productivity" },
new App { Name = "Adobe Premiere Pro", Description = "Videoschnittsoftware", Command = "winget install Adobe.PremierePro", IconClass = "bi-camera-video-fill", CategoryName = "Media" },
new App { Name = "Oracle VirtualBox", Description = "Open-Source-Virtualisierungssoftware", Command = "winget install Oracle.VirtualBox", IconClass = "bi-display", CategoryName = "Utility" },
new App { Name = "HandBrake", Description = "Open Source Video Converter", Command = "winget install HandBrake", IconClass = "bi-display", CategoryName = "Media" },
new App { Name = "PuTTY", Description = "Freie Implementierung von Telnet und SSH", Command = "winget install PuTTY", IconClass = "bi-terminal", CategoryName = "Utility" },
new App { Name = "Notion", Description = "Alles an einem Ort", Command = "winget install Notion", IconClass = "bi-files", CategoryName = "Productivity" },
new App { Name = "Adobe After Effects", Description = "Software für Animationen und Spezialeffekte", Command = "winget install Adobe.AfterEffects", IconClass = "bi-camera-reels", CategoryName = "Media" },
new App { Name = "Microsoft SQL Server Management Studio", Description = "Datenbankverwaltungstool", Command = "winget install Microsoft.SQLServerManagementStudio", IconClass = "bi-database", CategoryName = "Development" },
new App { Name = "Microsoft Power BI", Description = "Geschäftsanalysetool", Command = "winget install Microsoft.PowerBI", IconClass = "bi-bar-chart", CategoryName = "Productivity" },
new App { Name = "Blender", Description = "Open Source 3D-Modellierungssoftware", Command = "winget install Blender", IconClass = "bi-three-dots", CategoryName = "Design" },
new App { Name = "Microsoft Excel", Description = "Tabellenkalkulationsprogramm", Command = "winget install Microsoft.Excel", IconClass = "bi-table", CategoryName = "Productivity" },
new App { Name = "MySQL Workbench", Description = "Visuelles Datenbankdesignwerkzeug", Command = "winget install MySQL.Workbench", IconClass = "bi-patch-check", CategoryName = "Development" },
new App { Name = "Plex Media Server", Description = "Media-Server-Software", Command = "winget install Plex.MediaServer", IconClass = "bi-display", CategoryName = "Media" },
new App { Name = "Microsoft Outlook", Description = "E-Mail- und Kalenderanwendung", Command = "winget install Microsoft.Outlook", IconClass = "bi-envelope", CategoryName = "Communication" },
new App { Name = "Atom", Description = "Moderner Texteditor", Command = "winget install Atom", IconClass = "bi-file-richtext", CategoryName = "Development" },
new App { Name = "WinRAR", Description = "Packprogramm zur Datenkompression", Command = "winget install WinRAR", IconClass = "bi-archive", CategoryName = "Utility" },
new App { Name = "WhatsApp Desktop", Description = "Desktop-Version von WhatsApp", Command = "winget install WhatsApp", IconClass = "bi-phone", CategoryName = "Communication" },
new App { Name = "Telegram", Description = "Instant Messenger", Command = "winget install Telegram", IconClass = "bi-telegram", CategoryName = "Communication" },
new App { Name = "Microsoft OneDrive", Description = "Cloud-Speicher und Synchronisation", Command = "winget install Microsoft.OneDrive", IconClass = "bi-cloud-arrow-up", CategoryName = "Utility" },
new App { Name = "ZoomIt", Description = "Bildschirmzoom und Annotationstool", Command = "winget install ZoomIt", IconClass = "bi-zoom-in", CategoryName = "Utility" },
new App { Name = "Microsoft Edge", Description = "Webbrowser von Microsoft", Command = "winget install Microsoft.Edge", IconClass = "bi-globe", CategoryName = "Utility" },
new App { Name = "OpenVPN", Description = "Open Source VPN", Command = "winget install OpenVPN", IconClass = "bi-shield-lock", CategoryName = "Utility" },
new App { Name = "Visual Studio", Description = "Integrierte Entwicklungsumgebung (IDE)", Command = "winget install VisualStudio", IconClass = "bi-tools", CategoryName = "Development" },
new App { Name = "Sublime Text", Description = "Leistungsfähiger Texteditor für Code, Markup und Prosa", Command = "winget install SublimeText", IconClass = "bi-pencil", CategoryName = "Development" },
new App { Name = "Docker Desktop", Description = "Containerisierungsplattform", Command = "winget install DockerDesktop", IconClass = "bi-docker", CategoryName = "Development" },
new App { Name = "Microsoft Visio", Description = "Diagramm- und Flussdiagrammerstellungsprogramm", Command = "winget install Microsoft.Visio", IconClass = "bi-diagram-2", CategoryName = "Productivity" },
new App { Name = "Adobe Premiere Pro", Description = "Videoschnittsoftware", Command = "winget install Adobe.PremierePro", IconClass = "bi-camera-video-fill", CategoryName = "Media" },
new App { Name = "Oracle VirtualBox", Description = "Open-Source-Virtualisierungssoftware", Command = "winget install Oracle.VirtualBox", IconClass = "bi-display", CategoryName = "Utility" },
new App { Name = "HandBrake", Description = "Open Source Video Converter", Command = "winget install HandBrake", IconClass = "bi-display", CategoryName = "Media" },
new App { Name = "PuTTY", Description = "Freie Implementierung von Telnet und SSH", Command = "winget install PuTTY", IconClass = "bi-terminal", CategoryName = "Utility" },
new App { Name = "Notion", Description = "Alles an einem Ort", Command = "winget install Notion", IconClass = "bi-files", CategoryName = "Productivity" },
new App { Name = "Adobe After Effects", Description = "Software für Animationen und Spezialeffekte", Command = "winget install Adobe.AfterEffects", IconClass = "bi-camera-reels", CategoryName = "Media" },
new App { Name = "Microsoft SQL Server Management Studio", Description = "Datenbankverwaltungstool", Command = "winget install Microsoft.SQLServerManagementStudio", IconClass = "bi-database", CategoryName = "Development" },
new App { Name = "Microsoft Power BI", Description = "Geschäftsanalysetool", Command = "winget install Microsoft.PowerBI", IconClass = "bi-bar-chart", CategoryName = "Productivity" },
new App { Name = "Blender", Description = "Open Source 3D-Modellierungssoftware", Command = "winget install Blender", IconClass = "bi-three-dots", CategoryName = "Design" },
new App { Name = "Microsoft Excel", Description = "Tabellenkalkulationsprogramm", Command = "winget install Microsoft.Excel", IconClass = "bi-table", CategoryName = "Productivity" },
new App { Name = "MySQL Workbench", Description = "Visuelles Datenbankdesignwerkzeug", Command = "winget install MySQL.Workbench", IconClass = "bi-patch-check", CategoryName = "Development" },
new App { Name = "Plex Media Server", Description = "Media-Server-Software", Command = "winget install Plex.MediaServer", IconClass = "bi-display", CategoryName = "Media" },
new App { Name = "Microsoft Outlook", Description = "E-Mail- und Kalenderanwendung", Command = "winget install Microsoft.Outlook", IconClass = "bi-envelope", CategoryName = "Communication" },
new App { Name = "Wireshark", Description = "Netzwerkanalyse-Software", Command = "winget install Wireshark", IconClass = "bi-server", CategoryName = "Utility" },
new App { Name = "XAMPP", Description = "Webentwicklungsumgebung", Command = "winget install XAMPP", IconClass = "bi-server", CategoryName = "Development" },
new App { Name = "GIMP", Description = "Bildbearbeitungsprogramm", Command = "winget install GIMP", IconClass = "bi-image", CategoryName = "Design" },
new App { Name = "Discord", Description = "Sprach- und Textchat für Gamer", Command = "winget install Discord", IconClass = "bi-discord", CategoryName = "Gaming" },
new App { Name = "Visual Studio Code", Description = "Kostenloser Code-Editor von Microsoft", Command = "winget install VisualStudioCode", IconClass = "bi-code-slash", CategoryName = "Development" },
new App { Name = "GitHub Desktop", Description = "Grafische Benutzeroberfläche für GitHub", Command = "winget install GitHubDesktop", IconClass = "bi-github", CategoryName = "Development" },
new App { Name = "Google Chrome", Description = "Webbrowser von Google", Command = "winget install Google.Chrome", IconClass = "bi-globe2", CategoryName = "Utility" },
new App { Name = "Adobe Photoshop", Description = "Bildbearbeitungssoftware", Command = "winget install Adobe.Photoshop", IconClass = "bi-image", CategoryName = "Design" },
new App { Name = "Zoom", Description = "Videokonferenzsoftware", Command = "winget install Zoom", IconClass = "bi-camera-video", CategoryName = "Communication" },
new App { Name = "Slack", Description = "Kollaborationswerkzeug für Teams", Command = "winget install Slack", IconClass = "bi-slack", CategoryName = "Communication" },
new App { Name = "Spotify", Description = "Musik-Streaming-Dienst", Command = "winget install Spotify", IconClass = "bi-music-note", CategoryName = "Media" },
new App { Name = "Microsoft Teams", Description = "Kommunikations- und Kollaborationsplattform", Command = "winget install Microsoft.Teams", IconClass = "bi-chat", CategoryName = "Communication" },
new App { Name = "Notepad++", Description = "Kostenloser Texteditor für Windows", Command = "winget install NotepadPlusPlus", IconClass = "bi-file-code", CategoryName = "Development" },
new App { Name = "Adobe Acrobat Reader", Description = "PDF-Betrachter von Adobe", Command = "winget install Adobe.AcrobatReader", IconClass = "bi-file-pdf", CategoryName = "Utility" },
new App { Name = "VLC Media Player", Description = "Mediaplayer für verschiedene Audio- und Videoformate", Command = "winget install VLC.MediaPlayer", IconClass = "bi-play-circle", CategoryName = "Media" },
new App { Name = "Dropbox", Description = "Cloud-Speicher und Dateisynchronisation", Command = "winget install Dropbox", IconClass = "bi-cloud", CategoryName = "Utility" },
new App { Name = "Evernote", Description = "Notiz-App für Notizen und Ideen", Command = "winget install Evernote", IconClass = "bi-journal", CategoryName = "Productivity" },
new App { Name = "Microsoft Office", Description = "Bürosoftware-Suite von Microsoft", Command = "winget install Microsoft.Office", IconClass = "bi-file-earmark-text", CategoryName = "Productivity" },
new App { Name = "Adobe Illustrator", Description = "Vektorgrafiksoftware von Adobe", Command = "winget install Adobe.Illustrator", IconClass = "bi-vector-pen", CategoryName = "Design" },
new App { Name = "Audacity", Description = "Kostenloser Audio-Editor und -Recorder", Command = "winget install Audacity", IconClass = "bi-mic", CategoryName = "Media" },
new App { Name = "FileZilla", Description = "Kostenloser FTP-Client", Command = "winget install FileZilla", IconClass = "bi-server", CategoryName = "Utility" },
new App { Name = "Python", Description = "Programmiersprache", Command = "winget install Python", IconClass = "bi-python", CategoryName = "Development" },
new App { Name = "WinRAR", Description = "Packprogramm zur Datenkompression", Command = "winget install WinRAR", IconClass = "bi-archive", CategoryName = "Utility" },
new App { Name = "WhatsApp Desktop", Description = "Desktop-Version von WhatsApp", Command = "winget install WhatsApp", IconClass = "bi-phone", CategoryName = "Communication" },
new App { Name = "Telegram", Description = "Instant Messenger", Command = "winget install Telegram", IconClass = "bi-telegram", CategoryName = "Communication" },
new App { Name = "Microsoft OneDrive", Description = "Cloud-Speicher und Synchronisation", Command = "winget install Microsoft.OneDrive", IconClass = "bi-cloud-arrow-up", CategoryName = "Utility" },
new App { Name = "ZoomIt", Description = "Bildschirmzoom und Annotationstool", Command = "winget install ZoomIt", IconClass = "bi-zoom-in", CategoryName = "Utility" },
new App { Name = "Microsoft Edge", Description = "Webbrowser von Microsoft", Command = "winget install Microsoft.Edge", IconClass = "bi-globe", CategoryName = "Utility" },
new App { Name = "OpenVPN", Description = "Open Source VPN", Command = "winget install OpenVPN", IconClass = "bi-shield-lock", CategoryName = "Utility" },
new App { Name = "Visual Studio", Description = "Integrierte Entwicklungsumgebung (IDE)", Command = "winget install VisualStudio", IconClass = "bi-tools", CategoryName = "Development" },
new App { Name = "Sublime Text", Description = "Leistungsfähiger Texteditor für Code, Markup und Prosa", Command = "winget install SublimeText", IconClass = "bi-pencil", CategoryName = "Development" },
new App { Name = "Docker Desktop", Description = "Containerisierungsplattform", Command = "winget install DockerDesktop", IconClass = "bi-docker", CategoryName = "Development" },
new App { Name = "Microsoft Visio", Description = "Diagramm- und Flussdiagrammerstellungsprogramm", Command = "winget install Microsoft.Visio", IconClass = "bi-diagram-2", CategoryName = "Productivity" },
new App { Name = "Adobe Premiere Pro", Description = "Videoschnittsoftware", Command = "winget install Adobe.PremierePro", IconClass = "bi-camera-video-fill", CategoryName = "Media" },
new App { Name = "Oracle VirtualBox", Description = "Open-Source-Virtualisierungssoftware", Command = "winget install Oracle.VirtualBox", IconClass = "bi-display", CategoryName = "Utility" },
new App { Name = "HandBrake", Description = "Open Source Video Converter", Command = "winget install HandBrake", IconClass = "bi-display", CategoryName = "Media" },
new App { Name = "PuTTY", Description = "Freie Implementierung von Telnet und SSH", Command = "winget install PuTTY", IconClass = "bi-terminal", CategoryName = "Utility" },
new App { Name = "Notion", Description = "Alles an einem Ort", Command = "winget install Notion", IconClass = "bi-files", CategoryName = "Productivity" },
new App { Name = "Adobe After Effects", Description = "Software für Animationen und Spezialeffekte", Command = "winget install Adobe.AfterEffects", IconClass = "bi-camera-reels", CategoryName = "Media" },
new App { Name = "Microsoft SQL Server Management Studio", Description = "Datenbankverwaltungstool", Command = "winget install Microsoft.SQLServerManagementStudio", IconClass = "bi-database", CategoryName = "Development" },
new App { Name = "Microsoft Power BI", Description = "Geschäftsanalysetool", Command = "winget install Microsoft.PowerBI", IconClass = "bi-bar-chart", CategoryName = "Productivity" },
new App { Name = "Blender", Description = "Open Source 3D-Modellierungssoftware", Command = "winget install Blender", IconClass = "bi-three-dots", CategoryName = "Design" },
new App { Name = "Microsoft Excel", Description = "Tabellenkalkulationsprogramm", Command = "winget install Microsoft.Excel", IconClass = "bi-table", CategoryName = "Productivity" },
new App { Name = "MySQL Workbench", Description = "Visuelles Datenbankdesignwerkzeug", Command = "winget install MySQL.Workbench", IconClass = "bi-patch-check", CategoryName = "Development" },
new App { Name = "Plex Media Server", Description = "Media-Server-Software", Command = "winget install Plex.MediaServer", IconClass = "bi-display", CategoryName = "Media" },
new App { Name = "Microsoft Outlook", Description = "E-Mail- und Kalenderanwendung", Command = "winget install Microsoft.Outlook", IconClass = "bi-envelope", CategoryName = "Communication" },
new App { Name = "Wireshark", Description = "Netzwerkanalyse-Software", Command = "winget install Wireshark", IconClass = "bi-server", CategoryName = "Utility" },
new App { Name = "XAMPP", Description = "Webentwicklungsumgebung", Command = "winget install XAMPP", IconClass = "bi-server", CategoryName = "Development" },
new App { Name = "GIMP", Description = "Bildbearbeitungsprogramm", Command = "winget install GIMP", IconClass = "bi-image", CategoryName = "Design" },
new App { Name = "Discord", Description = "Sprach- und Textchat für Gamer", Command = "winget install Discord", IconClass = "bi-discord", CategoryName = "Gaming" },
new App { Name = "Visual Studio Code", Description = "Kostenloser Code-Editor von Microsoft", Command = "winget install VisualStudioCode", IconClass = "bi-code-slash", CategoryName = "Development" },
new App { Name = "GitHub Desktop", Description = "Grafische Benutzeroberfläche für GitHub", Command = "winget install GitHubDesktop", IconClass = "bi-github", CategoryName = "Development" },
new App { Name = "Google Chrome", Description = "Webbrowser von Google", Command = "winget install Google.Chrome", IconClass = "bi-globe2", CategoryName = "Utility" },
new App { Name = "Adobe Photoshop", Description = "Bildbearbeitungssoftware", Command = "winget install Adobe.Photoshop", IconClass = "bi-image", CategoryName = "Design" },
new App { Name = "Zoom", Description = "Videokonferenzsoftware", Command = "winget install Zoom", IconClass = "bi-camera-video", CategoryName = "Communication" },
new App { Name = "Slack", Description = "Kollaborationswerkzeug für Teams", Command = "winget install Slack", IconClass = "bi-slack", CategoryName = "Communication" },
new App { Name = "Spotify", Description = "Musik-Streaming-Dienst", Command = "winget install Spotify", IconClass = "bi-music-note", CategoryName = "Media" },
new App { Name = "Microsoft Teams", Description = "Kommunikations- und Kollaborationsplattform", Command = "winget install Microsoft.Teams", IconClass = "bi-chat", CategoryName = "Communication" },
new App { Name = "Notepad++", Description = "Kostenloser Texteditor für Windows", Command = "winget install NotepadPlusPlus", IconClass = "bi-file-code", CategoryName = "Development" },
new App { Name = "Adobe Acrobat Reader", Description = "PDF-Betrachter von Adobe", Command = "winget install Adobe.AcrobatReader", IconClass = "bi-file-pdf", CategoryName = "Utility" },
new App { Name = "VLC Media Player", Description = "Mediaplayer für verschiedene Audio- und Videoformate", Command = "winget install VLC.MediaPlayer", IconClass = "bi-play-circle", CategoryName = "Media" },
new App { Name = "Dropbox", Description = "Cloud-Speicher und Dateisynchronisation", Command = "winget install Dropbox", IconClass = "bi-cloud", CategoryName = "Utility" },
new App { Name = "Evernote", Description = "Notiz-App für Notizen und Ideen", Command = "winget install Evernote", IconClass = "bi-journal", CategoryName = "Productivity" },
new App { Name = "Microsoft Office", Description = "Bürosoftware-Suite von Microsoft", Command = "winget install Microsoft.Office", IconClass = "bi-file-earmark-text", CategoryName = "Productivity" },
new App { Name = "Adobe Illustrator", Description = "Vektorgrafiksoftware von Adobe", Command = "winget install Adobe.Illustrator", IconClass = "bi-vector-pen", CategoryName = "Design" },
new App { Name = "Audacity", Description = "Kostenloser Audio-Editor und -Recorder", Command = "winget install Audacity", IconClass = "bi-mic", CategoryName = "Media" },
new App { Name = "FileZilla", Description = "Kostenloser FTP-Client", Command = "winget install FileZilla", IconClass = "bi-server", CategoryName = "Utility" },
new App { Name = "Python", Description = "Programmiersprache", Command = "winget install Python", IconClass = "bi-python", CategoryName = "Development" },
new App { Name = "WinRAR", Description = "Packprogramm zur Datenkompression", Command = "winget install WinRAR", IconClass = "bi-archive", CategoryName = "Utility" },
new App { Name = "WhatsApp Desktop", Description = "Desktop-Version von WhatsApp", Command = "winget install WhatsApp", IconClass = "bi-phone", CategoryName = "Communication" },
new App { Name = "Telegram", Description = "Instant Messenger", Command = "winget install Telegram", IconClass = "bi-telegram", CategoryName = "Communication" },
new App { Name = "Microsoft OneDrive", Description = "Cloud-Speicher und Synchronisation", Command = "winget install Microsoft.OneDrive", IconClass = "bi-cloud-arrow-up", CategoryName = "Utility" },
new App { Name = "ZoomIt", Description = "Bildschirmzoom und Annotationstool", Command = "winget install ZoomIt", IconClass = "bi-zoom-in", CategoryName = "Utility" },
new App { Name = "Microsoft Edge", Description = "Webbrowser von Microsoft", Command = "winget install Microsoft.Edge", IconClass = "bi-globe", CategoryName = "Utility" },
new App { Name = "OpenVPN", Description = "Open Source VPN", Command = "winget install OpenVPN", IconClass = "bi-shield-lock", CategoryName = "Utility" },
new App { Name = "Visual Studio", Description = "Integrierte Entwicklungsumgebung (IDE)", Command = "winget install VisualStudio", IconClass = "bi-tools", CategoryName = "Development" },
new App { Name = "Sublime Text", Description = "Leistungsfähiger Texteditor für Code, Markup und Prosa", Command = "winget install SublimeText", IconClass = "bi-pencil", CategoryName = "Development" },
new App { Name = "Docker Desktop", Description = "Containerisierungsplattform", Command = "winget install DockerDesktop", IconClass = "bi-docker", CategoryName = "Development" },
new App { Name = "Microsoft Visio", Description = "Diagramm- und Flussdiagrammerstellungsprogramm", Command = "winget install Microsoft.Visio", IconClass = "bi-diagram-2", CategoryName = "Productivity" },
new App { Name = "Adobe Premiere Pro", Description = "Videoschnittsoftware", Command = "winget install Adobe.PremierePro", IconClass = "bi-camera-video-fill", CategoryName = "Media" },
new App { Name = "Oracle VirtualBox", Description = "Open-Source-Virtualisierungssoftware", Command = "winget install Oracle.VirtualBox", IconClass = "bi-display", CategoryName = "Utility" },
new App { Name = "HandBrake", Description = "Open Source Video Converter", Command = "winget install HandBrake", IconClass = "bi-display", CategoryName = "Media" },
new App { Name = "PuTTY", Description = "Freie Implementierung von Telnet und SSH", Command = "winget install PuTTY", IconClass = "bi-terminal", CategoryName = "Utility" },
new App { Name = "Notion", Description = "Alles an einem Ort", Command = "winget install Notion", IconClass = "bi-files", CategoryName = "Productivity" },
new App { Name = "Adobe After Effects", Description = "Software für Animationen und Spezialeffekte", Command = "winget install Adobe.AfterEffects", IconClass = "bi-camera-reels", CategoryName = "Media" },
new App { Name = "Microsoft SQL Server Management Studio", Description = "Datenbankverwaltungstool", Command = "winget install Microsoft.SQLServerManagementStudio", IconClass = "bi-database", CategoryName = "Development" },
new App { Name = "Microsoft Power BI", Description = "Geschäftsanalysetool", Command = "winget install Microsoft.PowerBI", IconClass = "bi-bar-chart", CategoryName = "Productivity" },
new App { Name = "Blender", Description = "Open Source 3D-Modellierungssoftware", Command = "winget install Blender", IconClass = "bi-three-dots", CategoryName = "Design" },
new App { Name = "Microsoft Excel", Description = "Tabellenkalkulationsprogramm", Command = "winget install Microsoft.Excel", IconClass = "bi-table", CategoryName = "Productivity" },
new App { Name = "MySQL Workbench", Description = "Visuelles Datenbankdesignwerkzeug", Command = "winget install MySQL.Workbench", IconClass = "bi-patch-check", CategoryName = "Development" },
new App { Name = "Plex Media Server", Description = "Media-Server-Software", Command = "winget install Plex.MediaServer", IconClass = "bi-display", CategoryName = "Media" },
new App { Name = "Microsoft Outlook", Description = "E-Mail- und Kalenderanwendung", Command = "winget install Microsoft.Outlook", IconClass = "bi-envelope", CategoryName = "Communication" },
new App { Name = "Wireshark", Description = "Netzwerkanalyse-Software", Command = "winget install Wireshark", IconClass = "bi-server", CategoryName = "Utility" },
new App { Name = "XAMPP", Description = "Webentwicklungsumgebung", Command = "winget install XAMPP", IconClass = "bi-server", CategoryName = "Development" },
new App { Name = "GIMP", Description = "Bildbearbeitungsprogramm", Command = "winget install GIMP", IconClass = "bi-image", CategoryName = "Design" },
new App { Name = "Discord", Description = "Sprach- und Textchat für Gamer", Command = "winget install Discord", IconClass = "bi-discord", CategoryName = "Gaming" },
new App { Name = "Visual Studio Code", Description = "Kostenloser Code-Editor von Microsoft", Command = "winget install VisualStudioCode", IconClass = "bi-code-slash", CategoryName = "Development" },
new App { Name = "GitHub Desktop", Description = "Grafische Benutzeroberfläche für GitHub", Command = "winget install GitHubDesktop", IconClass = "bi-github", CategoryName = "Development" },
new App { Name = "Google Chrome", Description = "Webbrowser von Google", Command = "winget install Google.Chrome", IconClass = "bi-globe2", CategoryName = "Utility" },
new App { Name = "Adobe Photoshop", Description = "Bildbearbeitungssoftware", Command = "winget install Adobe.Photoshop", IconClass = "bi-image", CategoryName = "Design" },
new App { Name = "Zoom", Description = "Videokonferenzsoftware", Command = "winget install Zoom", IconClass = "bi-camera-video", CategoryName = "Communication" },
new App { Name = "Slack", Description = "Kollaborationswerkzeug für Teams", Command = "winget install Slack", IconClass = "bi-slack", CategoryName = "Communication" },
new App { Name = "Spotify", Description = "Musik-Streaming-Dienst", Command = "winget install Spotify", IconClass = "bi-music-note", CategoryName = "Media" },
new App { Name = "Microsoft Teams", Description = "Kommunikations- und Kollaborationsplattform", Command = "winget install Microsoft.Teams", IconClass = "bi-chat", CategoryName = "Communication" },
new App { Name = "Notepad++", Description = "Kostenloser Texteditor für Windows", Command = "winget install NotepadPlusPlus", IconClass = "bi-file-code", CategoryName = "Development" },
new App { Name = "Adobe Acrobat Reader", Description = "PDF-Betrachter von Adobe", Command = "winget install Adobe.AcrobatReader", IconClass = "bi-file-pdf", CategoryName = "Utility" },
new App { Name = "VLC Media Player", Description = "Mediaplayer für verschiedene Audio- und Videoformate", Command = "winget install VLC.MediaPlayer", IconClass = "bi-play-circle", CategoryName = "Media" },
new App { Name = "Dropbox", Description = "Cloud-Speicher und Dateisynchronisation", Command = "winget install Dropbox", IconClass = "bi-cloud", CategoryName = "Utility" },
new App { Name = "Evernote", Description = "Notiz-App für Notizen und Ideen", Command = "winget install Evernote", IconClass = "bi-journal", CategoryName = "Productivity" },
new App { Name = "Microsoft Office", Description = "Bürosoftware-Suite von Microsoft", Command = "winget install Microsoft.Office", IconClass = "bi-file-earmark-text", CategoryName = "Productivity" },
new App { Name = "Adobe Illustrator", Description = "Vektorgrafiksoftware von Adobe", Command = "winget install Adobe.Illustrator", IconClass = "bi-vector-pen", CategoryName = "Design" },
new App { Name = "Audacity", Description = "Kostenloser Audio-Editor und -Recorder", Command = "winget install Audacity", IconClass = "bi-mic", CategoryName = "Media" },
new App { Name = "FileZilla", Description = "Kostenloser FTP-Client", Command = "winget install FileZilla", IconClass = "bi-server", CategoryName = "Utility" },
new App { Name = "Python", Description = "Programmiersprache", Command = "winget install Python", IconClass = "bi-python", CategoryName = "Development" },
new App { Name = "WinRAR", Description = "Packprogramm zur Datenkompression", Command = "winget install WinRAR", IconClass = "bi-archive", CategoryName = "Utility" },
new App { Name = "WhatsApp Desktop", Description = "Desktop-Version von WhatsApp", Command = "winget install WhatsApp", IconClass = "bi-phone", CategoryName = "Communication" },
new App { Name = "Telegram", Description = "Instant Messenger", Command = "winget install Telegram", IconClass = "bi-telegram", CategoryName = "Communication" },
new App { Name = "Microsoft OneDrive", Description = "Cloud-Speicher und Synchronisation", Command = "winget install Microsoft.OneDrive", IconClass = "bi-cloud-arrow-up", CategoryName = "Utility" },
new App { Name = "ZoomIt", Description = "Bildschirmzoom und Annotationstool", Command = "winget install ZoomIt", IconClass = "bi-zoom-in", CategoryName = "Utility" },
new App { Name = "Microsoft Edge", Description = "Webbrowser von Microsoft", Command = "winget install Microsoft.Edge", IconClass = "bi-globe", CategoryName = "Utility" },
new App { Name = "OpenVPN", Description = "Open Source VPN", Command = "winget install OpenVPN", IconClass = "bi-shield-lock", CategoryName = "Utility" },
new App { Name = "Visual Studio", Description = "Integrierte Entwicklungsumgebung (IDE)", Command = "winget install VisualStudio", IconClass = "bi-tools", CategoryName = "Development" },
new App { Name = "Sublime Text", Description = "Leistungsfähiger Texteditor für Code, Markup und Prosa", Command = "winget install SublimeText", IconClass = "bi-pencil", CategoryName = "Development" },
new App { Name = "Docker Desktop", Description = "Containerisierungsplattform", Command = "winget install DockerDesktop", IconClass = "bi-docker", CategoryName = "Development" },
new App { Name = "Microsoft Visio", Description = "Diagramm- und Flussdiagrammerstellungsprogramm", Command = "winget install Microsoft.Visio", IconClass = "bi-diagram-2", CategoryName = "Productivity" },
new App { Name = "Adobe Premiere Pro", Description = "Videoschnittsoftware", Command = "winget install Adobe.PremierePro", IconClass = "bi-camera-video-fill", CategoryName = "Media" },
new App { Name = "Oracle VirtualBox", Description = "Open-Source-Virtualisierungssoftware", Command = "winget install Oracle.VirtualBox", IconClass = "bi-display", CategoryName = "Utility" },
new App { Name = "HandBrake", Description = "Open Source Video Converter", Command = "winget install HandBrake", IconClass = "bi-display", CategoryName = "Media" },
new App { Name = "PuTTY", Description = "Freie Implementierung von Telnet und SSH", Command = "winget install PuTTY", IconClass = "bi-terminal", CategoryName = "Utility" },
new App { Name = "Notion", Description = "Alles an einem Ort", Command = "winget install Notion", IconClass = "bi-files", CategoryName = "Productivity" },
new App { Name = "Adobe After Effects", Description = "Software für Animationen und Spezialeffekte", Command = "winget install Adobe.AfterEffects", IconClass = "bi-camera-reels", CategoryName = "Media" },
new App { Name = "Microsoft SQL Server Management Studio", Description = "Datenbankverwaltungstool", Command = "winget install Microsoft.SQLServerManagementStudio", IconClass = "bi-database", CategoryName = "Development" },
new App { Name = "Microsoft Power BI", Description = "Geschäftsanalysetool", Command = "winget install Microsoft.PowerBI", IconClass = "bi-bar-chart", CategoryName = "Productivity" },
new App { Name = "Blender", Description = "Open Source 3D-Modellierungssoftware", Command = "winget install Blender", IconClass = "bi-three-dots", CategoryName = "Design" },
new App { Name = "Microsoft Excel", Description = "Tabellenkalkulationsprogramm", Command = "winget install Microsoft.Excel", IconClass = "bi-table", CategoryName = "Productivity" },
new App { Name = "MySQL Workbench", Description = "Visuelles Datenbankdesignwerkzeug", Command = "winget install MySQL.Workbench", IconClass = "bi-patch-check", CategoryName = "Development" },
new App { Name = "Plex Media Server", Description = "Media-Server-Software", Command = "winget install Plex.MediaServer", IconClass = "bi-display", CategoryName = "Media" },
new App { Name = "Microsoft Outlook", Description = "E-Mail- und Kalenderanwendung", Command = "winget install Microsoft.Outlook", IconClass = "bi-envelope", CategoryName = "Communication" },
new App { Name = "Wireshark", Description = "Netzwerkanalyse-Software", Command = "winget install Wireshark", IconClass = "bi-server", CategoryName = "Utility" },
new App { Name = "XAMPP", Description = "Webentwicklungsumgebung", Command = "winget install XAMPP", IconClass = "bi-server", CategoryName = "Development" },
new App { Name = "GIMP", Description = "Bildbearbeitungsprogramm", Command = "winget install GIMP", IconClass = "bi-image", CategoryName = "Design" },
new App { Name = "Discord", Description = "Sprach- und Textchat für Gamer", Command = "winget install Discord", IconClass = "bi-discord", CategoryName = "Gaming" },
new App { Name = "Visual Studio Code", Description = "Kostenloser Code-Editor von Microsoft", Command = "winget install VisualStudioCode", IconClass = "bi-code-slash", CategoryName = "Development" },
new App { Name = "GitHub Desktop", Description = "Grafische Benutzeroberfläche für GitHub", Command = "winget install GitHubDesktop", IconClass = "bi-github", CategoryName = "Development" },
new App { Name = "Google Chrome", Description = "Webbrowser von Google", Command = "winget install Google.Chrome", IconClass = "bi-globe2", CategoryName = "Utility" },
new App { Name = "Adobe Photoshop", Description = "Bildbearbeitungssoftware", Command = "winget install Adobe.Photoshop", IconClass = "bi-image", CategoryName = "Design" },
new App { Name = "Zoom", Description = "Videokonferenzsoftware", Command = "winget install Zoom", IconClass = "bi-camera-video", CategoryName = "Communication" },
new App { Name = "Slack", Description = "Kollaborationswerkzeug für Teams", Command = "winget install Slack", IconClass = "bi-slack", CategoryName = "Communication" },
new App { Name = "Spotify", Description = "Musik-Streaming-Dienst", Command = "winget install Spotify", IconClass = "bi-music-note", CategoryName = "Media" },
new App { Name = "Microsoft Teams", Description = "Kommunikations- und Kollaborationsplattform", Command = "winget install Microsoft.Teams", IconClass = "bi-chat", CategoryName = "Communication" },
new App { Name = "Notepad++", Description = "Kostenloser Texteditor für Windows", Command = "winget install NotepadPlusPlus", IconClass = "bi-file-code", CategoryName = "Development" },
new App { Name = "Adobe Acrobat Reader", Description = "PDF-Betrachter von Adobe", Command = "winget install Adobe.AcrobatReader", IconClass = "bi-file-pdf", CategoryName = "Utility" },
new App { Name = "VLC Media Player", Description = "Mediaplayer für verschiedene Audio- und Videoformate", Command = "winget install VLC.MediaPlayer", IconClass = "bi-play-circle", CategoryName = "Media" },
new App { Name = "Dropbox", Description = "Cloud-Speicher und Dateisynchronisation", Command = "winget install Dropbox", IconClass = "bi-cloud", CategoryName = "Utility" },
new App { Name = "Evernote", Description = "Notiz-App für Notizen und Ideen", Command = "winget install Evernote", IconClass = "bi-journal", CategoryName = "Productivity" },
new App { Name = "Microsoft Office", Description = "Bürosoftware-Suite von Microsoft", Command = "winget install Microsoft.Office", IconClass = "bi-file-earmark-text", CategoryName = "Productivity" },
new App { Name = "Adobe Illustrator", Description = "Vektorgrafiksoftware von Adobe", Command = "winget install Adobe.Illustrator", IconClass = "bi-vector-pen", CategoryName = "Design" },
new App { Name = "Audacity", Description = "Kostenloser Audio-Editor und -Recorder", Command = "winget install Audacity", IconClass = "bi-mic", CategoryName = "Media" },
new App { Name = "FileZilla", Description = "Kostenloser FTP-Client", Command = "winget install FileZilla", IconClass = "bi-server", CategoryName = "Utility" },
new App { Name = "Python", Description = "Programmiersprache", Command = "winget install Python", IconClass = "bi-python", CategoryName = "Development" },
new App { Name = "WinRAR", Description = "Packprogramm zur Datenkompression", Command = "winget install WinRAR", IconClass = "bi-archive", CategoryName = "Utility" },
new App { Name = "WhatsApp Desktop", Description = "Desktop-Version von WhatsApp", Command = "winget install WhatsApp", IconClass = "bi-phone", CategoryName = "Communication" },


                // Weitere Apps hier hinzufügen...
            };
        if (categoryName != null)
        {
            return apps.Where(app => app.CategoryName == categoryName).ToList();
        }

        return apps;
    }

    public List<App> GetAllApps()
    {
        return GetAppsByCategory(null);
    }



}

    

    public partial class App
    {
    public string Name { get; set; }
    public string Description { get; set; }
    public string Color { get; set; }
    public string IconClass { get; set; }
    public string Command { get; set; }
    public string CategoryName { get; set; }
} 
