namespace Instalify_V3;
using System.Collections.Generic;

public class AppDataService
{
    public List<App> GetAllApps()
    {
        return new List<App>
        {
            new App { Name = "Steam", Description = "Plattform für Spiele und soziale Interaktion", Command = "winget install Steam", IconClass = "bi-joystick" },
            new App { Name = "Discord", Description = "Sprach- und Textchat für Gamer", Command = "winget install Discord", IconClass = "bi-discord" },
            new App { Name = "Visual Studio Code", Description = "Kostenloser Code-Editor von Microsoft", Command = "winget install VisualStudioCode", IconClass = "bi-code-slash" },
            new App { Name = "GitHub Desktop", Description = "Grafische Benutzeroberfläche für GitHub", Command = "winget install GitHubDesktop", IconClass = "bi-github" },
            new App { Name = "Google Chrome", Description = "Webbrowser von Google", Command = "winget install Google.Chrome", IconClass = "bi-globe2" },
            new App { Name = "Adobe Photoshop", Description = "Bildbearbeitungssoftware", Command = "winget install Adobe.Photoshop", IconClass = "bi-image" },
            new App { Name = "Zoom", Description = "Videokonferenzsoftware", Command = "winget install Zoom", IconClass = "bi-camera-video" },
            new App { Name = "Slack", Description = "Kollaborationswerkzeug für Teams", Command = "winget install Slack", IconClass = "bi-slack" },
            new App { Name = "Spotify", Description = "Musik-Streaming-Dienst", Command = "winget install Spotify", IconClass = "bi-music-note" },
            new App { Name = "Microsoft Teams", Description = "Kommunikations- und Kollaborationsplattform", Command = "winget install Microsoft.Teams", IconClass = "bi-chat" },
            new App { Name = "Notepad++", Description = "Kostenloser Texteditor für Windows", Command = "winget install NotepadPlusPlus", IconClass = "bi-file-code" },
            new App { Name = "Adobe Acrobat Reader", Description = "PDF-Betrachter von Adobe", Command = "winget install Adobe.AcrobatReader", IconClass = "bi-file-pdf" },
            new App { Name = "VLC Media Player", Description = "Mediaplayer für verschiedene Audio- und Videoformate", Command = "winget install VLC.MediaPlayer", IconClass = "bi-play-circle" },
            new App { Name = "Dropbox", Description = "Cloud-Speicher und Dateisynchronisation", Command = "winget install Dropbox", IconClass = "bi-cloud" },
            new App { Name = "Evernote", Description = "Notiz-App für Notizen und Ideen", Command = "winget install Evernote", IconClass = "bi-journal" },
            new App { Name = "Microsoft Office", Description = "Bürosoftware-Suite von Microsoft", Command = "winget install Microsoft.Office", IconClass = "bi-file-earmark-text" },
            new App { Name = "Adobe Illustrator", Description = "Vektorgrafiksoftware von Adobe", Command = "winget install Adobe.Illustrator", IconClass = "bi-vector-pen" },
            new App { Name = "Audacity", Description = "Kostenloser Audio-Editor und -Recorder", Command = "winget install Audacity", IconClass = "bi-mic" },
            new App { Name = "FileZilla", Description = "Kostenloser FTP-Client", Command = "winget install FileZilla", IconClass = "bi-server" },
            new App { Name = "Python", Description = "Programmiersprache", Command = "winget install Python", IconClass = "bi-python" },
            new App { Name = "Atom", Description = "Moderner Texteditor", Command = "winget install Atom", IconClass = "bi-file-richtext" },
            new App { Name = "WinRAR", Description = "Packprogramm zur Datenkompression", Command = "winget install WinRAR", IconClass = "bi-archive" },
            new App { Name = "WhatsApp Desktop", Description = "Desktop-Version von WhatsApp", Command = "winget install WhatsApp", IconClass = "bi-phone" },
            new App { Name = "Telegram", Description = "Instant Messenger", Command = "winget install Telegram", IconClass = "bi-telegram" },
            new App { Name = "Microsoft OneDrive", Description = "Cloud-Speicher und Synchronisation", Command = "winget install Microsoft.OneDrive", IconClass = "bi-cloud-arrow-up" },
            new App { Name = "ZoomIt", Description = "Bildschirmzoom und Annotationstool", Command = "winget install ZoomIt", IconClass = "bi-zoom-in" },
            new App { Name = "Microsoft Edge", Description = "Webbrowser von Microsoft", Command = "winget install Microsoft.Edge", IconClass = "bi-globe" },
            new App { Name = "OpenVPN", Description = "Open Source VPN", Command = "winget install OpenVPN", IconClass = "bi-shield-lock" },
            new App { Name = "Visual Studio", Description = "Integrierte Entwicklungsumgebung (IDE)", Command = "winget install VisualStudio", IconClass = "bi-tools" },
            new App { Name = "Sublime Text", Description = "Leistungsfähiger Texteditor für Code, Markup und Prosa", Command = "winget install SublimeText", IconClass = "bi-pencil" },
            new App { Name = "Docker Desktop", Description = "Containerisierungsplattform", Command = "winget install DockerDesktop", IconClass = "bi-docker" },
            new App { Name = "Microsoft Visio", Description = "Diagramm- und Flussdiagrammerstellungsprogramm", Command = "winget install Microsoft.Visio", IconClass = "bi-diagram-2" },
            new App { Name = "Adobe Premiere Pro", Description = "Videoschnittsoftware", Command = "winget install Adobe.PremierePro", IconClass = "bi-camera-video-fill" },
            new App { Name = "Oracle VirtualBox", Description = "Open-Source-Virtualisierungssoftware", Command = "winget install Oracle.VirtualBox", IconClass = "bi-display" },
            new App { Name = "HandBrake", Description = "Open Source Video Converter", Command = "winget install HandBrake", IconClass = "bi-display" },
            new App { Name = "PuTTY", Description = "Freie Implementierung von Telnet und SSH", Command = "winget install PuTTY", IconClass = "bi-terminal" },
            new App { Name = "Notion", Description = "Alles an einem Ort", Command = "winget install Notion", IconClass = "bi-files" },
            new App { Name = "Adobe After Effects", Description = "Software für Animationen und Spezialeffekte", Command = "winget install Adobe.AfterEffects", IconClass = "bi-camera-reels" },
            new App { Name = "Microsoft SQL Server Management Studio", Description = "Datenbankverwaltungstool", Command = "winget install Microsoft.SQLServerManagementStudio", IconClass = "bi-database" },
            new App { Name = "Microsoft Power BI", Description = "Geschäftsanalysetool", Command = "winget install Microsoft.PowerBI", IconClass = "bi-bar-chart" },
            new App { Name = "Blender", Description = "Open Source 3D-Modellierungssoftware", Command = "winget install Blender", IconClass = "bi-three-dots" },
            new App { Name = "Microsoft Excel", Description = "Tabellenkalkulationsprogramm", Command = "winget install Microsoft.Excel", IconClass = "bi-table" },
            new App { Name = "MySQL Workbench", Description = "Visuelles Datenbankdesignwerkzeug", Command = "winget install MySQL.Workbench", IconClass = "bi-patch-check" },
            new App { Name = "Plex Media Server", Description = "Media-Server-Software", Command = "winget install Plex.MediaServer", IconClass = "bi-display" },
            new App { Name = "Microsoft Outlook", Description = "E-Mail- und Kalender-App", Command = "winget install Microsoft.Outlook", IconClass = "bi-envelope" },
            new App { Name = "iTunes", Description = "Medienplayer, Medienbibliothek und Online-Radiosender", Command = "winget install iTunes", IconClass = "bi-music-note-list" },
            new App { Name = "TeamViewer", Description = "Fernzugriffs- und Supportsoftware", Command = "winget install TeamViewer", IconClass = "bi-cursor" },
            new App { Name = "Visual Studio Community", Description = "Kostenlose IDE für kleine Teams", Command = "winget install VisualStudioCommunity", IconClass = "bi-tools" },
            new App { Name = "GIMP", Description = "Kostenlose Bildbearbeitungssoftware", Command = "winget install GIMP", IconClass = "bi-image-alt" },
            new App { Name = "Adobe Lightroom", Description = "Bildbearbeitungssoftware", Command = "winget install Adobe.Lightroom", IconClass = "bi-palette" },
            new App { Name = "Jupyter Notebook", Description = "Interaktives Webinterface für Datenanalyse", Command = "winget install JupyterNotebook", IconClass = "bi-journal" },
            new App { Name = "Origin", Description = "Plattform für Spiele und soziale Interaktion", Command = "winget install Origin", IconClass = "bi-joystick" },
            new App { Name = "Microsoft Project", Description = "Projekt- und Portfoliomanagementsoftware", Command = "winget install Microsoft.Project", IconClass = "bi-diagram-3" },
            new App { Name = "Microsoft Access", Description = "Datenbankverwaltungssystem", Command = "winget install Microsoft.Access", IconClass = "bi-journal" },
            new App { Name = "Google Drive", Description = "Cloud-Speicher und Dateisynchronisation", Command = "winget install Google.Drive", IconClass = "bi-cloud" },
            new App { Name = "Microsoft Publisher", Description = "Desktop-Publishing-Software", Command = "winget install Microsoft.Publisher", IconClass = "bi-journal" },
            new App { Name = "Microsoft Azure Storage Explorer", Description = "Datenverwaltung für Azure-Speicherkonten", Command = "winget install Microsoft.AzureStorageExplorer", IconClass = "bi-cloud" },
            new App { Name = "Microsoft Azure Data Studio", Description = "Kostenloses, plattformübergreifendes Datenmanagementtool", Command = "winget install Microsoft.AzureDataStudio", IconClass = "bi-diagram-3" },
            new App { Name = "Wireshark", Description = "Netzwerkprotokollanalysator", Command = "winget install Wireshark", IconClass = "bi-wifi" },
            new App { Name = "Postman", Description = "API-Test- und Entwicklungsumgebung", Command = "winget install Postman", IconClass = "bi-terminal" },
            new App { Name = "Arduino IDE", Description = "Entwicklungsumgebung für Arduino", Command = "winget install ArduinoIDE", IconClass = "bi-terminal" },
            new App { Name = "Microsoft OneNote", Description = "Digitales Notizbuch", Command = "winget install Microsoft.OneNote", IconClass = "bi-journal" },
            new App { Name = "Adobe InDesign", Description = "Layout-Software", Command = "winget install Adobe.Indesign", IconClass = "bi-layout-text-window" },
            new App { Name = "Microsoft Edge Dev", Description = "Webbrowser (Entwicklerversion)", Command = "winget install Microsoft.EdgeDev", IconClass = "bi-globe" },
            new App { Name = "Microsoft Edge Canary", Description = "Webbrowser (Canary-Version)", Command = "winget install Microsoft.EdgeCanary", IconClass = "bi-globe" },
            new App { Name = "Cisco Webex Meetings", Description = "Videokonferenzlösung", Command = "winget install Cisco.WebexMeetings", IconClass = "bi-camera-video" },
            new App { Name = "JetBrains Rider", Description = "IDE für .NET-Entwicklung", Command = "winget install JetBrains.Rider", IconClass = "bi-tools" },
            new App { Name = "JetBrains PhpStorm", Description = "IDE für PHP-Entwicklung", Command = "winget install JetBrains.PhpStorm", IconClass = "bi-tools" },
            new App { Name = "JetBrains PyCharm", Description = "IDE für Python-Entwicklung", Command = "winget install JetBrains.PyCharm", IconClass = "bi-tools" },
            new App { Name = "JetBrains IntelliJ IDEA", Description = "IDE für Java-Entwicklung", Command = "winget install JetBrains.IntelliJIDEA", IconClass = "bi-tools" },
            new App { Name = "JetBrains WebStorm", Description = "IDE für Web-Entwicklung", Command = "winget install JetBrains.WebStorm", IconClass = "bi-tools" },
            new App { Name = "JetBrains GoLand", Description = "IDE für Go-Entwicklung", Command = "winget install JetBrains.GoLand", IconClass = "bi-tools" },
            new App { Name = "JetBrains RubyMine", Description = "IDE für Ruby-Entwicklung", Command = "winget install JetBrains.RubyMine", IconClass = "bi-tools" },
            new App { Name = "JetBrains CLion", Description = "IDE für C/C++-Entwicklung", Command = "winget install JetBrains.CLion", IconClass = "bi-tools" },
            new App { Name = "JetBrains DataGrip", Description = "IDE für Datenbankentwicklung", Command = "winget install JetBrains.DataGrip", IconClass = "bi-tools" },
            new App { Name = "JetBrains AppCode", Description = "IDE für Objective-C und Swift-Entwicklung", Command = "winget install JetBrains.AppCode", IconClass = "bi-tools" },
            new App { Name = "JetBrains ReSharper", Description = "Erweiterung für .NET-Entwicklung in Visual Studio", Command = "winget install JetBrains.ReSharper", IconClass = "bi-tools" },
            new App { Name = "JetBrains Rider EAP", Description = "Frühe Zugriffsversion von Rider", Command = "winget install JetBrains.RiderEAP", IconClass = "bi-tools" },
            new App { Name = "JetBrains IntelliJ IDEA EAP", Description = "Frühe Zugriffsversion von IntelliJ IDEA", Command = "winget install JetBrains.IntelliJIDEAEAP", IconClass = "bi-tools" },
            new App { Name = "JetBrains PhpStorm EAP", Description = "Frühe Zugriffsversion von PhpStorm", Command = "winget install JetBrains.PhpStormEAP", IconClass = "bi-tools" },
            new App { Name = "JetBrains PyCharm EAP", Description = "Frühe Zugriffsversion von PyCharm", Command = "winget install JetBrains.PyCharmEAP", IconClass = "bi-tools" },
            new App { Name = "JetBrains GoLand EAP", Description = "Frühe Zugriffsversion von GoLand", Command = "winget install JetBrains.GoLandEAP", IconClass = "bi-tools" },
            new App { Name = "JetBrains WebStorm EAP", Description = "Frühe Zugriffsversion von WebStorm", Command = "winget install JetBrains.WebStormEAP", IconClass = "bi-tools" },
            new App { Name = "JetBrains RubyMine EAP", Description = "Frühe Zugriffsversion von RubyMine", Command = "winget install JetBrains.RubyMineEAP", IconClass = "bi-tools" },
            new App { Name = "JetBrains CLion EAP", Description = "Frühe Zugriffsversion von CLion", Command = "winget install JetBrains.CLionEAP", IconClass = "bi-tools" },
            new App { Name = "JetBrains DataGrip EAP", Description = "Frühe Zugriffsversion von DataGrip", Command = "winget install JetBrains.DataGripEAP", IconClass = "bi-tools" },
            new App { Name = "JetBrains AppCode EAP", Description = "Frühe Zugriffsversion von AppCode", Command = "winget install JetBrains.AppCodeEAP", IconClass = "bi-tools" },
            new App { Name = "JetBrains ReSharper EAP", Description = "Frühe Zugriffsversion von ReSharper", Command = "winget install JetBrains.ReSharperEAP", IconClass = "bi-tools" },
            new App { Name = "XAMPP", Description = "Webserverlösungspaket", Command = "winget install XAMPP", IconClass = "bi-server" },
            new App { Name = "WiX Toolset", Description = "Werkzeugsammlung für die Erstellung von Windows-Installationsprogrammen", Command = "winget install WiX.Toolset", IconClass = "bi-tools" },
            new App { Name = "TortoiseSVN", Description = "Subversion-Client für Windows", Command = "winget install TortoiseSVN", IconClass = "bi-code-slash" },
            new App { Name = "TortoiseGit", Description = "Git-Client für Windows", Command = "winget install TortoiseGit", IconClass = "bi-code-slash" },
            new App { Name = "PowerShell Core", Description = "Plattformübergreifende Version von PowerShell", Command = "winget install PowerShellCore", IconClass = "bi-terminal" },
            new App { Name = "7-Zip", Description = "Dateiarchivierer mit hoher Kompressionsrate", Command = "winget install 7-Zip", IconClass = "bi-archive" },
            new App { Name = "Mozilla Firefox", Description = "Webbrowser von Mozilla", Command = "winget install Mozilla.Firefox", IconClass = "bi-globe" },
            new App { Name = "Brave", Description = "Schneller und sicherer Webbrowser", Command = "winget install Brave", IconClass = "bi-globe" },
            new App { Name = "Kodi", Description = "Mediacenter-Software", Command = "winget install Kodi", IconClass = "bi-display" },
            new App { Name = "Node.js", Description = "JavaScript-Laufzeitumgebung", Command = "winget install Node.js", IconClass = "bi-node-js" },
            new App { Name = "Node.js LTS", Description = "Stabile Version von Node.js", Command = "winget install Node.jsLTS", IconClass = "bi-node-js" },
            new App { Name = "Google Earth Pro", Description = "Erweiterte Version der Google-Earth-Software", Command = "winget install Google.EarthPro", IconClass = "bi-globe" },
            new App { Name = "Google Earth", Description = "Erkundungs- und Bildbetrachtungssoftware", Command = "winget install Google.Earth", IconClass = "bi-globe" },
            new App { Name = "WhatsApp Desktop", Description = "Desktop-Version von WhatsApp", Command = "winget install WhatsAppDesktop", IconClass = "bi-phone" },
            new App { Name = "Microsoft Teams", Description = "Chat-basierte Arbeitsraum-App", Command = "winget install Microsoft.Teams", IconClass = "bi-chat" },
            new App { Name = "Signal", Description = "Verschlüsselte Messenger-App", Command = "winget install Signal", IconClass = "bi-chat" },
            new App { Name = "Telegram", Description = "Verschlüsselter Instant Messenger", Command = "winget install Telegram", IconClass = "bi-chat" },
            new App { Name = "Discord", Description = "Sprach-, Video- und Text-Chat für Gamer", Command = "winget install Discord", IconClass = "bi-chat" },
            new App { Name = "Zoom", Description = "Videokonferenzsoftware", Command = "winget install Zoom", IconClass = "bi-camera-video" },
            new App { Name = "Webex Teams", Description = "Kollaborationstool für Teams", Command = "winget install WebexTeams", IconClass = "bi-people" },
            new App { Name = "Skype", Description = "Messaging-, Sprach- und Videokonferenzsoftware", Command = "winget install Skype", IconClass = "bi-chat" },
            new App { Name = "VLC Media Player", Description = "Media-Player und Streaming-Server", Command = "winget install VLCMediaPlayer", IconClass = "bi-play-circle" },
            new App { Name = "GIMP", Description = "Bildbearbeitungsprogramm", Command = "winget install GIMP", IconClass = "bi-image" },
            new App { Name = "LibreOffice", Description = "Freie Bürosoftware-Suite", Command = "winget install LibreOffice", IconClass = "bi-file-earmark-text" },
            new App { Name = "Inkscape", Description = "Vektorgrafik-Editor", Command = "winget install Inkscape", IconClass = "bi-pen" },
            new App { Name = "Blender", Description = "3D-Creation-Suite", Command = "winget install Blender", IconClass = "bi-terminal" },
            new App { Name = "OpenShot", Description = "Videoschnitt- und Filmproduktionssoftware", Command = "winget install OpenShot", IconClass = "bi-play-circle" },
            new App { Name = "Audacity", Description = "Freier, plattformübergreifender Audio-Editor", Command = "winget install Audacity", IconClass = "bi-music-note" },
            new App { Name = "LMMS", Description = "Digital Audio Workstation", Command = "winget install LMMS", IconClass = "bi-music-note" },
            new App { Name = "OBS Studio", Description = "Live-Streaming-Software", Command = "winget install OBSStudio", IconClass = "bi-camera-video" },
            new App { Name = "Notepad++", Description = "Quelltext-Editor und Notizblock-Ersatz", Command = "winget install Notepad++", IconClass = "bi-terminal" },
            new App { Name = "Visual Studio Code", Description = "Quelltext-Editor und IDE", Command = "winget install VisualStudioCode", IconClass = "bi-terminal" },
            new App { Name = "Sublime Text", Description = "Quelltext-Editor für Code, Markup und Prosa", Command = "winget install SublimeText", IconClass = "bi-terminal" },
            new App { Name = "Atom", Description = "Quelltext-Editor und IDE", Command = "winget install Atom", IconClass = "bi-terminal" },
            new App { Name = "GitHub Desktop", Description = "Verbindung zu GitHub-Repositories", Command = "winget install GitHubDesktop", IconClass = "bi-github" },
            new App { Name = "Bitbucket", Description = "Git-Repository-Managementlösung", Command = "winget install Bitbucket", IconClass = "bi-github" },
            new App { Name = "NetBeans", Description = "Entwicklungsumgebung für Java", Command = "winget install NetBeans", IconClass = "bi-terminal" },
            new App { Name = "Eclipse", Description = "Entwicklungsumgebung für Java", Command = "winget install Eclipse", IconClass = "bi-terminal" },
            new App { Name = "Android Studio", Description = "Entwicklungsumgebung für Android", Command = "winget install AndroidStudio", IconClass = "bi-terminal" },
            new App { Name = "Unity Hub", Description = "Management von Unity-Installationsversionen", Command = "winget install UnityHub", IconClass = "bi-joystick" },
            new App { Name = "WinMerge", Description = "Visuelles Differenz- und Unterschiede-Werkzeug", Command = "winget install WinMerge", IconClass = "bi-terminal" },
            new App { Name = "FileZilla", Description = "FTP-Client", Command = "winget install FileZilla", IconClass = "bi-terminal" },
            new App { Name = "PuTTY", Description = "SSH- und Telnet-Client", Command = "winget install PuTTY", IconClass = "bi-terminal" },
            new App { Name = "RealVNC Viewer", Description = "Fernsteuerung von Computern", Command = "winget install RealVNCViewer", IconClass = "bi-terminal" },
            new App { Name = "IrfanView", Description = "Bildbetrachter und Konverter", Command = "winget install IrfanView", IconClass = "bi-image" },
            new App { Name = "CCleaner", Description = "PC-Optimierungs- und Reinigungstool", Command = "winget install CCleaner", IconClass = "bi-tools" },
            new App { Name = "ZoomIt", Description = "Präsentationstool für Bildschirmzoom und Anmerkungen", Command = "winget install ZoomIt", IconClass = "bi-joystick" },
            new App { Name = "Sourcetree", Description = "Kostenloser Git- und Mercurial-Client für Windows", Command = "winget install Sourcetree", IconClass = "bi-terminal" },
            new App { Name = "Babylon.js Editor", Description = "Webbasierte 3D-Game-Entwicklungsumgebung", Command = "winget install BabylonJsEditor", IconClass = "bi-terminal" },
            new App { Name = "Microsoft Forms", Description = "Erstellen von Umfragen, Umfragen und Quizzes", Command = "winget install Microsoft.Forms", IconClass = "bi-journal" },
            new App { Name = "Microsoft Whiteboard", Description = "Digitaler Whiteboard-Dienst", Command = "winget install Microsoft.Whiteboard", IconClass = "bi-journal" },
            new App { Name = "Microsoft Bookings", Description = "Online-Terminplanungs- und Buchungstool", Command = "winget install Microsoft.Bookings", IconClass = "bi-journal" },
            new App { Name = "Microsoft Kaizala", Description = "Dienst zur Verwaltung mobiler Geräte", Command = "winget install Microsoft.Kaizala", IconClass = "bi-journal" },
            new App { Name = "Microsoft To Do", Description = "Aufgabenverwaltung", Command = "winget install Microsoft.ToDo", IconClass = "bi-journal" },
            new App { Name = "Microsoft Forms Pro", Description = "Erstellen von Umfragen, Umfragen und Quizzes (Pro-Version)", Command = "winget install Microsoft.FormsPro", IconClass = "bi-journal" },
            new App { Name = "Microsoft Lists", Description = "Anwendungen zum Verfolgen von Informationen", Command = "winget install Microsoft.Lists", IconClass = "bi-journal" },
            new App { Name = "Microsoft Stream", Description = "Business-Video-Service", Command = "winget install Microsoft.Stream", IconClass = "bi-camera-video" },
            new App { Name = "Microsoft Sway", Description = "Interaktive Berichte, Präsentationen und mehr", Command = "winget install Microsoft.Sway", IconClass = "bi-journal" },
            new App { Name = "Microsoft Stream for Android", Description = "Business-Video-Service", Command = "winget install Microsoft.StreamForAndroid", IconClass = "bi-journal" },
            new App { Name = "Microsoft Lists for Android", Description = "Anwendungen zum Verfolgen von Informationen", Command = "winget install Microsoft.ListsForAndroid", IconClass = "bi-journal" },
            new App { Name = "Microsoft Kaizala for Android", Description = "Dienst zur Verwaltung mobiler Geräte", Command = "winget install Microsoft.KaizalaForAndroid", IconClass = "bi-journal" },

                // Weitere Apps hier hinzufügen...
            };
        }
    }

    public partial class App
    {
        public string Name { get; set; }
        public string Description { get; set; }
        public string Command { get; set; }
        public string Color { get; set; }
        public string IconClass { get; set; }
    } 
